Probably finished but untested

diff --git a/dlgmsg2html b/dlgmsg2html
--- a/dlgmsg2html
+++ b/dlgmsg2html
@@ -1,51 +1,195 @@
 #!/bin/bash
 #
-# $Id: dlgmsg2html,v 1.2 2004-03-27 22:49:25 psy Exp $
+# $Id: dlgmsg2html,v 1.3 2004-03-28 16:58:32 psy Exp $
 #
-# This shell script parses DLG (Dialog) messages and produces HTML pages.
+# This script parses files containing DLG messages and produces XHTML pages.
+# Input consists of text files xx1, xx2, etc.; output consists
+# of XHTML 1.0 files xx1.html, xx2.html, etc.
+#
+# Copyright (C) 2004 Tristan Miller <psychonaut@nothingisreal.com>
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 
-echo Processing $1... 1>&2
+# Set up some variables
+PROGRAMNAME="dlgmsg2html"
+PROGRAMVERSION="v1.0"
+PROGRAMCOPYRIGHT="2004 Tristan Miller"
+WELCOME="$PROGRAMNAME $PROGRAMVERSION
+Copyright (C) $PROGRAMCOPYRIGHT
+This is free software; see the source for copying conditions.  There is NO
+warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
+PREFIX="xx"
+TITLE=""
 
-FROM=`head -1 $1 | cut -c12-43 | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-TO=`head -2 $1 | tail -1 | cut -c12-43 | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-DATE=`head -3 $1 | tail -1 | cut -c12- | sed -e 's/ 93 / 1993 /'`
-SUBJECT=`head -4 $1 | tail -1 | cut -c12- | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-MSG=`head -1 $1 | sed -e 's/^.*MSG //;s/ OF.*//'`
+# Usage instructions
+ME=`basename $0`
+USAGE="Usage: $ME [options]
 
-if fgrep '[Reply To' $1 >&/dev/null
+General options:
+    -t TITLE        use TITLE for document title
+    -p PREFIX       use PREFIX instead of \`xx'
+    -?, --help      output this message and exit
+    -v, --version   output version information and exit
+"
+
+# Error function
+function error() # errormessage
+{
+    echo "$ME: $1" 1>&2
+}
+
+# Parse command line
+while [ $# -gt 0 ]
+do
+    case $1 in
+    -p)        shift
+	       if [ $# -eq 0 ]
+	       then
+		    error "no prefix specified"
+		    exit 1
+	       fi
+	       PREFIX="$1"
+	       ;;
+    -p)        shift
+	       if [ $# -eq 0 ]
+	       then
+		    error "no title specified"
+		    exit 1
+	       fi
+	       TITLE="$1: "
+	       ;;
+    -\?)       echo "$USAGE"; exit 0    ;;
+    --\?)      echo "$USAGE"; exit 0    ;;
+    --help)    echo "$USAGE"; exit 0    ;;
+    -v)        echo "$WELCOME"; exit 0    ;;
+    --version) echo "$WELCOME"; exit 0    ;;
+    *)         error "invalid argument \`$1'"
+	       exit 1 ;;
+    esac
+    shift
+done
+if [ `ls -1 $PREFIX* | wc -l` -eq 0 ]
 then
-    REF=`head -2 $1 | tail -1 | sed -e 's/^.*Reply To //;s/\].*//'`
-    REF_FROM=`head -1 $PREFIX$REF | cut -c12-43 | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-    REF_SUBJECT=`head -4 $PREFIX$REF | tail -1 | cut -c12- | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+    error "no message files matching prefix \`$PREFIX'"
+    exit 1
 fi
 
-if fgrep '[Has Reply' $1 >&/dev/null
-then
-    REPLY=`head -2 $1 | tail -1 | sed -e 's/^.*Has Reply //;s/\].*//'`
-    REPLY_FROM=`head -1 $PREFIX$REPLY | cut -c12-43 | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-    REPLY_SUBJECT=`head -4 $PREFIX$REPLY | tail -1 | cut -c12- | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-fi
+# Determine first and last message numbers
+FIRST_MSG=`ls -1 $PREFIX* \
+    | sort -n -k 1.$((${#PREFIX}+1)) \
+    | head -1 \
+    | cut -c$((${#PREFIX}+1))-`
+LAST_MSG=`ls -1 $PREFIX* \
+    | sort -n -k 1.$((${#PREFIX}+1)) \
+    | tail -1 \
+    | cut -c$((${#PREFIX}+1))-`
 
-if [ $MSG -lt $LAST_MSG ]
-then
-    NEXT=`ls -1 $PREFIX* | sort -n -k 1.4 | grep "^$PREFIX$MSG\$" -A 1 | tail -1 | cut -c4-`
-    NEXT_FROM=`head -1 $PREFIX$NEXT | cut -c12-43 | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-    NEXT_SUBJECT=`head -4 $PREFIX$NEXT | tail -1 | cut -c12- | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-fi
+# For each message
+for F in $PREFIX*
+do
+    echo Processing $F... 1>&2
 
-if [ $MSG -gt $FIRST_MSG ]
-then
-    PREV=`ls -1 $PREFIX* | sort -n -k 1.4 | grep "^$PREFIX$MSG\$" -B 1 | head -1 | cut -c4-`
-    PREV_FROM=`head -1 $PREFIX$PREV | cut -c12-43 | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-    PREV_SUBJECT=`head -4 $PREFIX$PREV | tail -1 | cut -c12- | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
-fi
+    # Extract header data
+    FROM=`head -1 $F \
+	| cut -c12-43 \
+	| sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+    TO=`head -2 $F \
+	| tail -1 \
+	| cut -c12-43 \
+	| sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+    DATE=`head -3 $F \
+	| tail -1 \
+	| cut -c12-`
+    SUBJECT=`head -4 $F \
+	| tail -1 \
+	| cut -c12- \
+	| sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+    MSG=`head -1 $F \
+	| sed -e 's/^.*MSG //;s/ OF.*//'`
 
-cat <<EOF
+    # Extract header data from referenced message
+    if fgrep '[Reply To' $F >&/dev/null
+    then
+	REF=`head -2 $F \
+	    | tail -1 \
+	    | sed -e 's/^.*Reply To //;s/\].*//'`
+	REF_FROM=`head -1 $PREFIX$REF \
+	    | cut -c12-43 \
+	    | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+	REF_SUBJECT=`head -4 $PREFIX$REF \
+	    | tail -1 \
+	    | cut -c12- \
+	    | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+    fi
+
+    # Extract header data from reply
+    if fgrep '[Has Reply' $F >&/dev/null
+    then
+	REPLY=`head -2 $F \
+	    | tail -1 \
+	    | sed -e 's/^.*Has Reply //;s/\].*//'`
+	REPLY_FROM=`head -1 $PREFIX$REPLY \
+	    | cut -c12-43 \
+	    | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+	REPLY_SUBJECT=`head -4 $PREFIX$REPLY \
+	    | tail -1 \
+	    | cut -c12- \
+	    | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+    fi
+
+    # Extract header data from next message
+    if [ $MSG -lt $LAST_MSG ]
+    then
+	NEXT=`ls -1 $PREFIX* \
+	    | sort -n -k 1.$((${#PREFIX}+1)) \
+	    | grep "^$PREFIX$MSG\$" -A 1 \
+	    | tail -1 \
+	    | cut -c$((${#PREFIX}+1))-`
+	NEXT_FROM=`head -1 $PREFIX$NEXT \
+	    | cut -c12-43 \
+	    | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+	NEXT_SUBJECT=`head -4 $PREFIX$NEXT \
+	    | tail -1 \
+	    | cut -c12- \
+	    | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+    fi
+
+    # Extract header data from previous message
+    if [ $MSG -gt $FIRST_MSG ]
+    then
+	PREV=`ls -1 $PREFIX* \
+	    | sort -n -k 1.$((${#PREFIX}+1)) \
+	    | grep "^$PREFIX$MSG\$" -B 1 \
+	    | head -1 \
+	    | cut -c$((${#PREFIX}+1))-`
+	PREV_FROM=`head -1 $PREFIX$PREV \
+	    | cut -c12-43 \
+	    | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+	PREV_SUBJECT=`head -4 $PREFIX$PREV \
+	    | tail -1 \
+	    | cut -c12- \
+	    | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
+    fi
+
+    # Output XHTML
+    cat >$F.html <<EOF
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
   <head>
     <meta http-equiv="Content-Type" content="text/html; charset=us-ascii" />
-    <title>$TITLE: $SUBJECT</title>
+    <title>$TITLE$SUBJECT</title>
     <link rel="Start" href="index.html" />
     <link rel="Top" href="index.html" />
     <link rel="Up" href="index.html" />
@@ -54,19 +198,19 @@ cat <<EOF
     <link rel="Index" href="index_date.html" />  
     <link rel="Last" href="$PREFIX$LAST_MSG.html" />  
 EOF
-if [ $MSG -lt $LAST_MSG ]
-then
-    cat <<EOF
+    if [ $MSG -lt $LAST_MSG ]
+    then
+	cat >$F.html <<EOF
     <link rel="Next" href="$PREFIX$NEXT.html" />  
 EOF
-fi
-if [ $MSG -gt $FIRST_MSG ]
-then
-    cat <<EOF
+    fi
+    if [ $MSG -gt $FIRST_MSG ]
+    then
+	cat >$F.html <<EOF
     <link rel="Prev" href="$PREFIX$PREV.html" />  
 EOF
-fi
-cat <<EOF
+    fi
+    cat >$F.html <<EOF
     <style type="text/css">
       <!--
 	th {text-align: right}
@@ -82,31 +226,31 @@ cat <<EOF
     </table>
     <table style="padding-left: 3em; font-size: smaller">
 EOF
-if [ $MSG -lt $LAST_MSG ]
-then
-    cat <<EOF
+    if [ $MSG -lt $LAST_MSG ]
+    then
+	cat >$F.html <<EOF
       <tr><th>Next message:</th><td><a href="$PREFIX$NEXT.html">$NEXT_FROM: $NEXT_SUBJECT</a></td></tr>
 EOF
-fi
-if [ $MSG -gt $FIRST_MSG ]
-then
-    cat <<EOF
+    fi
+    if [ $MSG -gt $FIRST_MSG ]
+    then
+	cat >$F.html <<EOF
       <tr><th>Previous message:</th><td><a href="$PREFIX$PREV.html">$PREV_FROM: $PREV_SUBJECT</a></td></tr>
 EOF
-fi
-if [ $REF ]
-then
-    cat <<EOF
+    fi
+    if [ $REF ]
+    then
+	cat >$F.html <<EOF
       <tr><th>In reply to:</th><td><a href="$PREFIX$REF.html">$REF_FROM: $REF_SUBJECT</a></td></tr>
 EOF
-fi
-if [ $REPLY ]
-then
-    cat <<EOF
+    fi
+    if [ $REPLY ]
+    then
+	cat >$F.html <<EOF
       <tr><th>Reply:</th><td><a href="$PREFIX$REPLY.html">$REPLY_FROM: $REPLY_SUBJECT</a></td></tr>
 EOF
-fi
-cat <<EOF
+    fi
+    cat >$F.html <<EOF
       <tr><th>Messages sorted by:</th><td>[&nbsp;<a
 	    href="index_date.html">date</a>&nbsp;] [&nbsp;<a
 	    href="index_subject.html">subject</a>&nbsp;] [&nbsp;<a
@@ -115,11 +259,13 @@ cat <<EOF
     <hr />
 <pre>
 EOF
-sed '1,5d;s/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g' $1
-cat <<EOF
+    sed '1,5d;s/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g' $F >$F.html
+    cat >$F.html <<EOF
 </pre>
     <hr />
     <p>Generated by <a style="font-size: smaller" href="http://www.nothingisreal.com/dlg2html/">dlg2html 1.0</a></p>
   </body>
 </html>
 EOF
+
+done
